// <auto-generated />
using GraphQLProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLProject.Migrations
{
    [DbContext(typeof(GraphQLDbContext))]
    partial class GraphQLDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQLProject.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Menus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A juicy chicken burger with lettuce and cheese",
                            Name = "Burger",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tomato and fresh lettuce",
                            Name = "Salad",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tortilla ",
                            Name = "Burrito",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 4,
                            Description = "Creamy Alfredo sauce with fettuccine pasta",
                            Name = "Pasta Alfredo",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 5,
                            Description = "Warm chocolate brownie with ice cream",
                            Name = "Chocolate",
                            Price = 10.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
